---
title: "nfl_null_function"
author: "logan lapace"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
null_values <- function(data, name) {
  
  data[data == ""] <- NA
  null_counts <- colSums(is.na(data))
  data_name <- name
  x = paste("Null Value Counts by Column: ",data_name) 
  result_null_check <- data.frame(Column = names(null_counts), NullCount = null_counts)

  # Print the formatted table using kable and kableExtra
  result_table <- result_null_check %>%
    kable("html", align = c("l", "c"), caption = x , col.names = c("Column", "NullCount"), row.names = FALSE) %>%
    kable_styling(full_width = FALSE)
  
  return(result_table)
}
```
#Injury_data: In the injury dataset, the examination of null values reveals that all columns, except for "PlayKey," are free of missing data. However, "PlayKey" exhibits 28 null values. Possible explanations for this could include data recording errors, where the play key information might not have been recorded or documented properly during the data collection process. It could also be attributed to instances where the specific plays associated with injuries are genuinely unknown or not applicable. Further investigation into the nature of these null values, such as examining the corresponding records or consulting additional data sources, may provide insights into the reasons behind the missing "PlayKey" entries and inform appropriate strategies for handling or imputing this missing information.

#PlayerTD: The "PlayerTD" dataset presents minimal missing data, with no null values in crucial columns such as "PlayKey" and "time." However, a substantial number of null values (74,526,875) in the "event" column suggest potential issues in recording or documenting specific events during plays. Additionally, two null values each in the "dir" and "o" columns may be attributed to plays where directional and orientation data were either not captured or were missing during the recording process.

#Playlist: Within the "PlayList" dataset, most columns exhibit no null values, providing a robust foundation for analysis. However, there are notable exceptions. The "StadiumType" column contains 16,910 null values, signifying gaps in information about the stadium type during games. Similarly, the "Weather" column has 18,691 null values, indicating missing data concerning weather conditions. The "PlayType" column also shows 367 null values, suggesting instances where the play type is unspecified or not recorded. Understanding the specific context of these missing values is essential for comprehensive data interpretation and appropriate handling.
