<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Matthew Wilcox, Randy Otoo, Logan Lapace" />


<title>Impact on Field Surface and Player Injuries</title>

<script src="Report_files/header-attrs-2.24/header-attrs.js"></script>
<script src="Report_files/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="Report_files/bootstrap-3.3.5/css/united.min.css" rel="stylesheet" />
<script src="Report_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="Report_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="Report_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="Report_files/navigation-1.1/tabsets.js"></script>
<script src="Report_files/navigation-1.1/codefolding.js"></script>
<link href="Report_files/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="Report_files/highlightjs-9.12.0/highlight.js"></script>
<script src="Report_files/kePrint-0.0.1/kePrint.js"></script>
<link href="Report_files/lightable-0.0.1/lightable.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>



<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Impact on Field Surface and Player
Injuries</h1>
<h4 class="author">Matthew Wilcox, Randy Otoo, Logan Lapace</h4>

</div>


<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>This year, fans of the NFL have watched their favorite teams compete
week in and week out. However, many fans are saddened and angered that
they have been unable to watch their favorite players not being on the
field due to injuries. Especially after Aaron Rodgers tore his Achilles
in the first game of the season, The NFLPA executive director Lloyd
Howell called upon all NFL owners to convert their stadium from turf to
grass, according to ESPN. With this recent outcry for the switch, we
want to see if there is a correlation between the field surface and the
injuries while comparing it with various factors.</p>
</div>
<div id="libraries" class="section level1">
<h1>Libraries</h1>
<pre class="r"><code>library(data.table)
library(tidyverse)
library(gridExtra)
library(png)
library(grid)
library(patchwork)
library(magrittr)
library(knitr)
library(kableExtra)</code></pre>
<pre><code>## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
## ✔ dplyr     1.1.3     ✔ readr     2.1.4
## ✔ forcats   1.0.0     ✔ stringr   1.5.0
## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
## ✔ purrr     1.0.2     
## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
## ✖ dplyr::between()     masks data.table::between()
## ✖ dplyr::filter()      masks stats::filter()
## ✖ dplyr::first()       masks data.table::first()
## ✖ lubridate::hour()    masks data.table::hour()
## ✖ lubridate::isoweek() masks data.table::isoweek()
## ✖ dplyr::lag()         masks stats::lag()
## ✖ dplyr::last()        masks data.table::last()
## ✖ lubridate::mday()    masks data.table::mday()
## ✖ lubridate::minute()  masks data.table::minute()
## ✖ lubridate::month()   masks data.table::month()
## ✖ lubridate::quarter() masks data.table::quarter()
## ✖ lubridate::second()  masks data.table::second()
## ✖ purrr::transpose()   masks data.table::transpose()
## ✖ lubridate::wday()    masks data.table::wday()
## ✖ lubridate::week()    masks data.table::week()
## ✖ lubridate::yday()    masks data.table::yday()
## ✖ lubridate::year()    masks data.table::year()
## ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors
## 
## Attaching package: &#39;gridExtra&#39;
## 
## 
## The following object is masked from &#39;package:dplyr&#39;:
## 
##     combine
## 
## 
## 
## Attaching package: &#39;magrittr&#39;
## 
## 
## The following object is masked from &#39;package:purrr&#39;:
## 
##     set_names
## 
## 
## The following object is masked from &#39;package:tidyr&#39;:
## 
##     extract
## 
## 
## 
## Attaching package: &#39;kableExtra&#39;
## 
## 
## The following object is masked from &#39;package:dplyr&#39;:
## 
##     group_rows</code></pre>
</div>
<div id="data-descrition" class="section level1">
<h1>Data Descrition</h1>
<pre class="r"><code>injury_data &lt;- fread(&quot;InjuryRecord.csv&quot;)

PlayerTD &lt;- fread(&quot;PlayerTrackData.csv&quot;)

PlayList &lt;- fread(&quot;PlayList.csv&quot;)</code></pre>
<p>The NFL 1st and Future - Analytics Kaggle Competition acquired the
data. This competition was Hosted in 2019 by the NFL to investigate the
relationship between the playing surface and the injury and performance
of NFL Athletes. This provided three datasets. The first consisted of
the injuries. This provided us with the Injury type, the player/play it
occurred on, and how long that player was out after that injury. The
second data set was of the player telemetry data. This data provided
information such as the player’s speed and the player’s movement for
individual plays. The final dataset gave us data on the plays. It showed
the person involved in the play, what type of play it was, the weather
at the time of the play, and finally, the field surface.</p>
<p>Data Source: <a
href="https://www.kaggle.com/competitions/nfl-playing-surface-analytics/data"
class="uri">https://www.kaggle.com/competitions/nfl-playing-surface-analytics/data</a></p>
</div>
<div id="data-cleaning" class="section level1">
<h1>Data Cleaning</h1>
<div
id="look-for-nulls-and-missing-data-summarize-how-many-missing-values-per-column.-ex-no-play-number-for-an-injury-where-player-didnt-exit-on-a-particular-play"
class="section level3">
<h3>look for nulls and missing data, summarize: how many missing values
per column. ex: no play number for an injury where player didnt exit on
a particular play</h3>
<pre class="r"><code>null_values &lt;- function(data, name) {
  
  data[data == &quot;&quot;] &lt;- NA
  null_counts &lt;- colSums(is.na(data))
  data_name &lt;- name
  x = paste(&quot;Null Value Counts by Column: &quot;,data_name) 
  result_null_check &lt;- data.frame(Column = names(null_counts), NullCount = null_counts)

  # Print the formatted table using kable and kableExtra
  result_table &lt;- result_null_check %&gt;%
    kable(&quot;html&quot;, align = c(&quot;l&quot;, &quot;c&quot;), caption = x , col.names = c(&quot;Column&quot;, &quot;NullCount&quot;), row.names = FALSE) %&gt;%
    kable_styling(full_width = FALSE)
  
  return(result_table)
}</code></pre>
<pre class="r"><code>null_values(injury_data, &#39;injury_data&#39;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Null Value Counts by Column: injury_data
</caption>
<thead>
<tr>
<th style="text-align:left;">
Column
</th>
<th style="text-align:center;">
NullCount
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
PlayerKey
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
GameID
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayKey
</td>
<td style="text-align:center;">
28
</td>
</tr>
<tr>
<td style="text-align:left;">
BodyPart
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Surface
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
DM_M1
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
DM_M7
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
DM_M28
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
DM_M42
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>null_values(PlayerTD, &#39;PlayerTD&#39;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Null Value Counts by Column: PlayerTD
</caption>
<thead>
<tr>
<th style="text-align:left;">
Column
</th>
<th style="text-align:center;">
NullCount
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
PlayKey
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
time
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
event
</td>
<td style="text-align:center;">
74526875
</td>
</tr>
<tr>
<td style="text-align:left;">
x
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
y
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
dir
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
dis
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
o
</td>
<td style="text-align:center;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
s
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>null_values(PlayList, &#39;PlayList&#39;)</code></pre>
<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
Null Value Counts by Column: PlayList
</caption>
<thead>
<tr>
<th style="text-align:left;">
Column
</th>
<th style="text-align:center;">
NullCount
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
PlayerKey
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
GameID
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayKey
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
RosterPosition
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayerDay
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayerGame
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
StadiumType
</td>
<td style="text-align:center;">
16910
</td>
</tr>
<tr>
<td style="text-align:left;">
FieldType
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Temperature
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Weather
</td>
<td style="text-align:center;">
18691
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayType
</td>
<td style="text-align:center;">
367
</td>
</tr>
<tr>
<td style="text-align:left;">
PlayerGamePlay
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Position
</td>
<td style="text-align:center;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
PositionGroup
</td>
<td style="text-align:center;">
0
</td>
</tr>
</tbody>
</table>
<p>Injury_data: In the injury dataset, the examination of null values
reveals that all columns, except for “PlayKey,” are free of missing
data. However, “PlayKey” exhibits 28 null values. Possible explanations
for this could include data recording errors, where the play key
information might not have been recorded or documented properly during
the data collection process. It could also be attributed to instances
where the specific plays associated with injuries are genuinely unknown
or not applicable. Further investigation into the nature of these null
values, such as examining the corresponding records or consulting
additional data sources, may provide insights into the reasons behind
the missing “PlayKey” entries and inform appropriate strategies for
handling or imputing this missing information.</p>
<p>PlayerTD: The “PlayerTD” dataset presents minimal missing data, with
no null values in crucial columns such as “PlayKey” and “time.” However,
a substantial number of null values (74,526,875) in the “event” column
suggest potential issues in recording or documenting specific events
during plays. Additionally, two null values each in the “dir” and “o”
columns may be attributed to plays where directional and orientation
data were either not captured or were missing during the recording
process.</p>
<p>Playlist: Within the “PlayList” dataset, most columns exhibit no null
values, providing a robust foundation for analysis. However, there are
notable exceptions. The “StadiumType” column contains 16,910 null
values, signifying gaps in information about the stadium type during
games. Similarly, the “Weather” column has 18,691 null values,
indicating missing data concerning weather conditions. The “PlayType”
column also shows 367 null values, suggesting instances where the play
type is unspecified or not recorded. Understanding the specific context
of these missing values is essential for comprehensive data
interpretation and appropriate handling.</p>
</div>
</div>
<div id="lower-body-injury-comparison" class="section level1">
<h1>Lower Body Injury Comparison</h1>
<pre class="r"><code>view(injury_data)
injury_data %&gt;% 
  ggplot(aes(BodyPart,
              fill = Surface)) +
  geom_bar(position = &quot;dodge&quot;, alpha = 1)+
  theme_bw()+
  theme( panel.grid.major = element_blank(),
         panel.grid.minor = element_blank()) +
  labs(x = &quot;Body Part&quot;,
       y = &quot;Number&quot;,
       title = &quot;Lower Body Injury Comparison&quot;) </code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<pre class="r"><code># Set plotting area into a 2*3 array
par(mfrow = c(2,3))

k.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Knee&quot;)

k.injury_df &lt;- k.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(k.injury_df))

k.injury.plot &lt;- ggplot(k.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0)+ ggtitle(&quot;Knee&quot;)
k.injury_df</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Surface    prop
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Natural     0.5
## 2 Synthetic   0.5</code></pre>
<pre class="r"><code>a.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Ankle&quot;)

a.injury_df &lt;- a.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(a.injury_df))

a.injury.plot&lt;- ggplot(a.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0)+ ggtitle(&quot;Ankle&quot;)
a.injury_df</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Surface    prop
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Natural   0.405
## 2 Synthetic 0.595</code></pre>
<pre class="r"><code>t.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Toes&quot;)

t.injury_df &lt;- t.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(t.injury_df))

t.injury.plot &lt;- ggplot(t.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0)

t.injury_df</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Surface    prop
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Natural   0.143
## 2 Synthetic 0.857</code></pre>
<pre class="r"><code>t.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Toes&quot;)

t.injury_df &lt;- t.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(t.injury_df))

t.injury.plot &lt;- ggplot(t.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0)+ ggtitle( &quot;Toe&quot;)
t.injury_df</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Surface    prop
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Natural   0.143
## 2 Synthetic 0.857</code></pre>
<pre class="r"><code>f.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Foot&quot;)

f.injury_df &lt;- f.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(f.injury_df))

f.injury.plot &lt;- ggplot(f.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0)+ ggtitle( &quot;Foot&quot;)
f.injury_df</code></pre>
<pre><code>## # A tibble: 2 × 2
##   Surface    prop
##   &lt;chr&gt;     &lt;dbl&gt;
## 1 Natural   0.714
## 2 Synthetic 0.286</code></pre>
<pre class="r"><code>h.injury_df &lt;- injury_data %&gt;% filter(BodyPart == &quot;Heel&quot;)

h.injury_df &lt;- h.injury_df %&gt;%
  select(BodyPart, Surface) %&gt;%
  group_by(Surface) %&gt;%
  summarise(prop = n()/nrow(h.injury_df))

h.injury.plot &lt;- ggplot(h.injury_df, aes(x = &quot;&quot;, y = prop, fill =  Surface)) + 
  geom_bar(stat = &quot;identity&quot;, width = 1)+
  coord_polar(&quot;y&quot;, start = 0) + ggtitle(&quot;Heel&quot;)
h.injury_df</code></pre>
<pre><code>## # A tibble: 1 × 2
##   Surface  prop
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 Natural     1</code></pre>
<pre class="r"><code>grid.arrange(k.injury.plot, 
             a.injury.plot,
             t.injury.plot, 
             f.injury.plot, 
             h.injury.plot, 
             nrow = 3, ncol = 3)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<pre class="r"><code>merged_data &lt;- merge(injury_data, PlayList, by = c(&quot;PlayerKey&quot;, &quot;GameID&quot;, &quot;PlayKey&quot;))

# merged_data &lt;- merge(merged_data, PlayerTD, by = &quot;PlayKey&quot;)

#distribution of injuries by field type
ggplot(merged_data, aes(x = FieldType, fill = BodyPart)) +
  geom_bar(position = &quot;stack&quot;) +
  labs(title = &quot;Injuries by Field Type and Body Part&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<pre class="r"><code>#distribution of injuries by field type as proportions
ggplot(merged_data, aes(x = FieldType, fill = BodyPart)) +
  geom_bar(position = &quot;fill&quot;) +
  labs(title = &quot;Proportion of Injuries by Field Type and Body Part&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-10-2.png" width="672" />
The first plot shows absolute injury counts stacked by body part, while
the second plot presents proportions of injuries by body part within
each field type. If “FieldType” refers to playing surface, a preliminary
observation suggests that synthetic turf may have a higher overall
injury count, with the second plot indicating a potential association
between synthetic turf and a higher proportion of ankle injuries
compared to natural turf.</p>
</div>
<div id="surface-impact-on-injury-length" class="section level1">
<h1>Surface impact on Injury Length</h1>
<pre class="r"><code>injury_data %&gt;%
  ggplot(aes(DM_M28,
             color = BodyPart,
             fill = BodyPart)) +
  geom_density(alpha = 0.4 , show.legend = F) +
  facet_grid(Surface ~ BodyPart) +
  labs(title = &quot;Surface impact on Injury Day&quot;,
       x = &quot;Day out for Injury&quot;,
       y = &quot;&quot;) +
  theme_bw()</code></pre>
<pre><code>## Warning: Groups with fewer than two data points have been dropped.
## Groups with fewer than two data points have been dropped.</code></pre>
<pre><code>## Warning in max(ids, na.rm = TRUE): no non-missing arguments to max; returning
## -Inf

## Warning in max(ids, na.rm = TRUE): no non-missing arguments to max; returning
## -Inf</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>injury_data$days_out &lt;- injury_data$DM_M1 + injury_data$DM_M7 + injury_data$DM_M28 + injury_data$DM_M42

Injury_len_df &lt;- injury_data %&gt;% select(BodyPart, Surface, days_out)

injury_len_df.natural &lt;- Injury_len_df %&gt;% filter( Surface == &quot;Natural&quot;) 
len_natural &lt;- nrow(injury_len_df.natural)
injury_len_df.natural &lt;- injury_len_df.natural %&gt;% group_by(days_out) %&gt;%
  summarise(prop = n()/len_natural)  
injury_len_df.natural$surface &lt;- &quot;Natural&quot;

injury_len_df.Synthetic &lt;- Injury_len_df %&gt;% filter( Surface == &quot;Synthetic&quot;) 
len_Synthetic &lt;- nrow(injury_len_df.Synthetic)
injury_len_df.Synthetic &lt;- injury_len_df.Synthetic %&gt;% group_by(days_out) %&gt;%
  summarise(prop = n()/len_Synthetic)  
injury_len_df.Synthetic$surface &lt;- &quot;Synthetic&quot;


Injury_len_df.surface_count &lt;- rbind(injury_len_df.natural, injury_len_df.Synthetic) %&gt;% 
  arrange(desc(days_out))
Injury_len_df.surface_count &lt;- Injury_len_df.surface_count %&gt;%
  mutate(days_out = case_when(
    days_out == 4 ~ &quot;42 + days&quot;,
    days_out == 3 ~ &quot;28-42 days&quot;,
    days_out == 2 ~ &quot;7-28 days&quot;, 
    days_out == 1 ~ &quot;1-7 days out&quot;
  ))
days_out_order &lt;- c(&quot;1-7 days out&quot;,&quot;7-28 days&quot;,&quot;28-42 days&quot;,&quot;42 + days&quot;)
Injury_len_df.surface_count$days_out &lt;- factor(Injury_len_df.surface_count$days_out, levels = days_out_order)


injury_len_map &lt;- ggplot(Injury_len_df.surface_count, aes(x=surface, y = days_out, fill = prop)) +
  geom_tile() + 
  geom_text(aes(label = paste(round(prop*100,3), &quot;%&quot;)))+
  scale_fill_gradientn(colors =  c(  &quot;white&quot;, &quot;orange&quot;)) + 
  ggtitle(&quot;Percentage of the Injury Length by Field Surface &quot;) +
  ylab(&quot;Days Out Injured&quot;) +
  xlab(&quot;Field Surface&quot;)
  
injury_len_map</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-12-1.png" width="672" />
The graph above shows the proportion of the injuries that happened on
synthetic and natural grass fields for the length of the injury. The two
field surfaces follow similar patterns with the length of the injury,
especially if the injury caused them to be out more than 42 days or
between 1 and 7 days. However, the biggest change is from 7-28 and 28-42
days. The injuries on natural grass had less from 28-42 and more from
7-28. For this data, the proportionally more players who got injured on
a Synthetic grass field for approximately a month or more while on grass
had proportionally more injuries lasting a couple of weeks.</p>
</div>
<div id="surface-and-weather" class="section level1">
<h1>Surface and Weather</h1>
<pre class="r"><code>ggplot(merged_data, aes(x = Weather, fill = BodyPart)) +
  geom_bar(position = &quot;stack&quot;) +
  labs(title = &quot;Injuries by Weather and Body Part&quot;) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  # Rotate x-axis labels</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<pre class="r"><code>ggplot(merged_data, aes(x = FieldType, fill = BodyPart)) +
  geom_bar(position = &quot;stack&quot;) +
  facet_wrap(~Weather) +
  labs(title = &quot;Injuries by Field Type and Body Part (Faceted by Weather)&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-2.png" width="672" /></p>
<pre class="r"><code>ggplot(merged_data, aes(x = FieldType, fill = BodyPart)) +
  geom_bar(position = &quot;fill&quot;) +  # Use position = &quot;fill&quot; for proportions
  facet_wrap(~Weather, scales = &quot;free_y&quot;) +  # Use scales = &quot;free_y&quot; for independent y-axes
  labs(title = &quot;Proportions of Injuries by Field Type and Body Part (Faceted by Weather)&quot;)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-3.png" width="672" /></p>
<pre class="r"><code># Heatmap for the correlation between field types, weather, and injuries
correlation_matrix &lt;- table(merged_data$FieldType, merged_data$Weather)
heatmap(correlation_matrix, main = &quot;Correlation Heatmap&quot;, 
        xlab = &quot;Weather&quot;, ylab = &quot;FieldType&quot;, col = heat.colors(12))</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-13-4.png" width="672" />
A stacked bar plot, visualizing the distribution of injuries by weather
conditions and body parts. the data reveals elevated injury counts under
weather conditions characterized by reduced visibility, such as cloudy,
partly cloudy, and sunny conditions. This observation prompts further
exploration into the potential correlation between weather patterns
impacting visibility and the occurrence of injuries.</p>
<p>The first plot provides a stacked bar chart depicting the
distribution of injuries across body parts on different field types
under various weather conditions. The second plot displays proportions
of injuries with independent y-axes, emphasizing the relative
contribution of body parts on distinct field types during different
weather conditions. Notably, the observations suggest a clear
correlation between synthetic turf and ankle injuries. Furthermore, the
heightened correlation between low visibility weather conditions and
injuries appears more pronounced for natural turf fields. Indoor fields
are almost always Synthetic turf, so low visibility conditions are not
going to apply very often to turf fields.</p>
<p>A heatmap showcasing the correlation between field types, weather
conditions, and injuries in the merged dataset. The heatmap, titled
“Correlation Heatmap,” visually confirms and reinforces the earlier
observations from the preceding analyses and visualizations, providing a
succinct summary of the interconnected factors influencing injury
patterns. Injuries are more evenly distrubuted across all weather
conditions for turf fields (which happen to be indoors more often),
while we notice a skew in the heat map for natural turf fields.</p>
</div>
<div id="player-movement-and-the-field-surface" class="section level1">
<h1>Player Movement and the Field Surface</h1>
<pre class="r"><code>get_max_play &lt;- function(input_df, play_col, play_val, max_column){
  df &lt;- input_df %&gt;% filter(!!as.symbol(play_col) == {{play_val}})
  max.val &lt;- max(df[[max_column]])
  max.val
}</code></pre>
<pre class="r"><code>Injury_speeds &lt;- lapply(as.list(injury_data$PlayKey), get_max_play, input_df = PlayerTD, play_col=&quot;PlayKey&quot;, max_column = &quot;s&quot;)
injury_data$Speeds &lt;- Injury_speeds</code></pre>
<pre class="r"><code>injury_data &lt;- na.omit(injury_data)
injury_data &lt;- injury_data %&gt;%
  select(BodyPart, Surface, Speeds, PlayKey)
injury_data$Speeds &lt;- as.numeric(injury_data$Speeds)
injury_data &lt;- injury_data[injury_data$Speeds &gt;= 0]</code></pre>
<p>We have looked at a variety of factors that could impact the injury
with relation to the field surface. But we havent discussed what the
individual was doing at the time of injury. With the telemetry data
provided we can observe this. The primary factor we are looking at is
going to be the speed on the player of the injury. For this it is not
just the speed but the max speed the player reached on the play.</p>
<pre class="r"><code>speed_synthetic &lt;-ggplot(injury_data[injury_data$Surface == &quot;Synthetic&quot;], aes(x=Speeds)) +
  geom_histogram(bins = 10) +
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  ggtitle(&quot;Speed at Injury on Synthetic&quot;)
speed_Natural &lt;- ggplot(injury_data[injury_data$Surface == &quot;Natural&quot;], aes(x=Speeds))+
  geom_histogram(bins = 10)+
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  ggtitle(&quot;Speed at Injury on Natural&quot;)
grid.arrange(speed_synthetic, speed_Natural, nrow = 1)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>These two graphs show the maximum speed on the play where the injury
occurred. What is seen is that on natural grass, the speed at which the
injury occurs appears to be a bit more uniform than on synthetic grass.
The synthetic graph appears slightly left skew, while natural grass has
a more uniform distribution. This could indicate that synthetic grass
has more injuries at higher speeds while natural grass is consistent in
its injuries at any speed.</p>
<pre class="r"><code>Knee_injury &lt;- injury_data[injury_data$BodyPart == &quot;Knee&quot;]
kspeed_synthetic &lt;-ggplot(Knee_injury[Knee_injury$Surface == &quot;Synthetic&quot;], aes(x=Speeds)) +
  geom_histogram(bins = 10, fill=&quot;Black&quot;) +
  ggtitle(&quot;Knee-Injury on Synthetic&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(1,10)+
  ylim(0,5)
kspeed_Natural &lt;- ggplot(Knee_injury[Knee_injury$Surface == &quot;Natural&quot;], aes(x=Speeds))+
  geom_histogram(bins = 10, fill = &quot;Black&quot;)+
  ggtitle(&quot;Knee-Injury on Natural&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(1,10)+
  ylim(0,5)

Ankle_injury &lt;- injury_data[injury_data$BodyPart == &quot;Ankle&quot;]
Ank.speed_synthetic &lt;-ggplot(Ankle_injury[Ankle_injury$Surface == &quot;Synthetic&quot;], aes(x=Speeds)) +
  geom_histogram(bins = 10, fill = &quot;Orange&quot;) +
  ggtitle(&quot;Ankle-Injury on Synthetic&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(1,10)+
  ylim(0,5)
Ank.speed_Natural &lt;- ggplot(Ankle_injury[Ankle_injury$Surface == &quot;Natural&quot;], aes(x=Speeds))+
  geom_histogram(bins = 10, fill = &quot;Orange&quot;)+
  ggtitle(&quot;Ankle-Injury on Natural&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(1,10)+
  ylim(0,5)

Foot_injury &lt;- injury_data[injury_data$BodyPart == &quot;Foot&quot;]
fo.speed_synthetic &lt;-ggplot(Foot_injury[Foot_injury$Surface == &quot;Synthetic&quot;], aes(x=Speeds)) +
  geom_histogram(bins = 10,fill = &quot;Sky Blue&quot;) +
  ggtitle(&quot;Foot-Injury on Synthetic&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(0,10)+
  ylim(0,5)
fo.speed_Natural &lt;- ggplot(Foot_injury[Foot_injury$Surface == &quot;Natural&quot;], aes(x=Speeds))+
  geom_histogram(bins = 10, fill = &quot;Sky Blue&quot;)+
  ggtitle(&quot;Foot-Injury on Natural&quot;) + 
  xlab(&quot;Speed (Yards Per Second)&quot;) +
  xlim(1,10)+
  ylim(0,5)


grid.arrange(kspeed_synthetic,Ank.speed_synthetic, fo.speed_synthetic,
             kspeed_Natural, Ank.speed_Natural, fo.speed_Natural,  ncol = 3)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-18-1.png" width="672" />
If we split out the injuries by the body part that the injury occurred
on we can get more insights. There are not enough foot injuries to
really determine a difference. For Knee injuries, the distributions are
relatively similar. However for Ankle injuries, there were more injuries
that occured at higher speeds on Synthetic Grass.</p>
</div>
<div id="player-movement" class="section level1">
<h1>Player Movement</h1>
<pre class="r"><code>Injury_plays &lt;- filter( PlayerTD,
  PlayKey %in% unique(injury_data$PlayKey)
)</code></pre>
<pre class="r"><code>graph_play &lt;- function(df, play, col, graph_name){
  df &lt;- filter(df, !!as.symbol(col) == {{play}})
  img &lt;- readPNG(&quot;football.png&quot;)
  g &lt;- rasterGrob(img, interpolate = TRUE)
  temp_name  &lt;- paste(&quot;Graph&quot;, gsub(&quot;-&quot;, &quot;_&quot;, play), sep = &quot;.&quot;)
  temp_graph &lt;- ggplot(df, aes(x,y, color = s))+
  xlim(0,120) + 
  ylim(0,53.3) + 
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point() + coord_flip()+
    scale_color_gradient(
      low = &quot;blue&quot;,
      high = &quot;orange&quot;,
      limits=c(0,10)
    )+ guides(fill = guide_legend(title= &quot;Speed&quot;))+
    geom_segment(aes(
      xend = c(tail(x, n=-1), NA),
      yend = c(tail(y, n=-1), NA)
    ))
  assign(graph_name, temp_graph, envir = .GlobalEnv)
}

# get_max_play &lt;- function(input_df, play_col, play_val, max_column){
#   df &lt;- input_df %&gt;% filter(!!as.symbol(play_col) == {{play_val}})
#   max.val &lt;- max(df[[max_column]])
#   max.val

# graph_play(PlayerTD, &quot;39873-4-32&quot;, &quot;PlayKey&quot;)

k.injury_play_list &lt;- unique(Knee_injury$PlayKey)
counter &lt;- 0
for(play in k.injury_play_list){
  graph_name &lt;- paste(&quot;g&quot;, counter, sep = &quot;&quot;)
  graph_play(PlayerTD, play, &quot;PlayKey&quot;, graph_name)
  counter &lt;- counter +1
}</code></pre>
<p>Below is visualizations of the plays that lead to the injuries. The
color of the dots represent the speed of the player at that moment where
they are on the field in the play. The injuries are only knee injuries
that occurred. One common trait that is observed is that in majority of
the plays that had knee injuries, the player was cutting and stopping
after going fast.</p>
<pre class="r"><code>(g0 | g1)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<pre class="r"><code>  (g2 | g3)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-2.png" width="672" /></p>
<pre class="r"><code>(g4 | g5)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-3.png" width="672" /></p>
<pre class="r"><code>  (g7 | g6)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-4.png" width="672" /></p>
<pre class="r"><code>(g8 | g9)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-5.png" width="672" /></p>
<pre class="r"><code>  (g11 | g10)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-6.png" width="672" /></p>
<pre class="r"><code>(g12 | g14)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-7.png" width="672" /></p>
<pre class="r"><code>  (g13 | g15)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-8.png" width="672" /></p>
<pre class="r"><code>(g19 | g16)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-9.png" width="672" /></p>
<pre class="r"><code>  (g18 | g17)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-10.png" width="672" /></p>
<pre class="r"><code>(g20 | g28)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-11.png" width="672" /></p>
<pre class="r"><code>  (g21 | g29)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-12.png" width="672" /></p>
<pre class="r"><code>(g22 | g30)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-13.png" width="672" /></p>
<pre class="r"><code>  (g23 | g31)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-14.png" width="672" /></p>
<pre class="r"><code>(g24 | g32)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-15.png" width="672" /></p>
<pre class="r"><code>  (g25 | g33)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-16.png" width="672" /></p>
<pre class="r"><code>(g26 | g34)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-17.png" width="672" /></p>
<pre class="r"><code>  (g27 | g35)</code></pre>
<p><img src="Report_files/figure-html/unnamed-chunk-21-18.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
